package fr.prunetwork.network.server;

import javax.swing.JTextField;

/**
 *
 * @author jpierre03
 */
public class MainServeurGUI extends javax.swing.JFrame{

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	/** Indique si un serveur Multi client existe*/
	private boolean isExistMonServeurMultiClient = false;
	//private MonServeurMultiClient msMC = null;

	/** Creates new form MainServeurGUI */
	public MainServeurGUI(){
		initComponents();
	}

	/*public void setMonServeurMultiClient(MonServeurMultiClient msMC) {
	this.msMC = msMC;
	System.err.println("setMonServeurMultiClient - ok");
	}*/
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contoleServeurJPanel = new javax.swing.JPanel();
        startJButton = new javax.swing.JButton();
        stateJPanel = new javax.swing.JPanel();
        stateJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startJButton.setText("Lancer Serveur");
        startJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contoleServeurJPanelLayout = new javax.swing.GroupLayout(contoleServeurJPanel);
        contoleServeurJPanel.setLayout(contoleServeurJPanelLayout);
        contoleServeurJPanelLayout.setHorizontalGroup(
            contoleServeurJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contoleServeurJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startJButton)
                .addContainerGap())
        );
        contoleServeurJPanelLayout.setVerticalGroup(
            contoleServeurJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contoleServeurJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stateJTextField.setFocusable(false);
        stateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stateJPanelLayout = new javax.swing.GroupLayout(stateJPanel);
        stateJPanel.setLayout(stateJPanelLayout);
        stateJPanelLayout.setHorizontalGroup(
            stateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stateJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        stateJPanelLayout.setVerticalGroup(
            stateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contoleServeurJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contoleServeurJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJButtonActionPerformed

		final JTextField state = stateJTextField;
		if(isExistMonServeurMultiClient != true){
			new Thread(){

				@Override
				public void run(){
					state.setText("Serveur Créé ");
					System.out.println("Serveur Créé ");
					//setMonServeurMultiClient(new MonServeurMultiClient(0));
					new MonServeurMultiClient(0);
				}
			}.start();
		}
		isExistMonServeurMultiClient = true;
    }//GEN-LAST:event_startJButtonActionPerformed

    private void stateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJTextFieldActionPerformed
		// TODO add your handling code here:
		// unused
    }//GEN-LAST:event_stateJTextFieldActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]){
		java.awt.EventQueue.invokeLater(new Runnable(){

			@Override
			public void run(){
				MainServeurGUI mainServeurGUI = new MainServeurGUI();
				mainServeurGUI.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contoleServeurJPanel;
    private javax.swing.JButton startJButton;
    private javax.swing.JPanel stateJPanel;
    private javax.swing.JTextField stateJTextField;
    // End of variables declaration//GEN-END:variables
}
