package fr.prunetwork.network.client;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Created on 16 nov. 2009, 15:28:02
 * @author jpierre03
 */
public class MainClient extends javax.swing.JFrame{

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form MainClient */
	public MainClient(){
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        monClientJPannelGUI = new fr.prunetwork.network.client.MonClientJPannelGUI();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileJMenu = new javax.swing.JMenu();
        exitJMenuItem = new javax.swing.JMenuItem();
        openFileJMenuItem = new javax.swing.JMenuItem();
        editJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(monClientJPannelGUI);

        FileJMenu.setText("File");

        exitJMenuItem.setText("Ouvrir Fichier");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        FileJMenu.add(exitJMenuItem);

        openFileJMenuItem.setText("Quitter");
        openFileJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileJMenuItemActionPerformed(evt);
            }
        });
        FileJMenu.add(openFileJMenuItem);

        jMenuBar1.add(FileJMenu);

        editJMenu.setText("Edit");
        jMenuBar1.add(editJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
		monClientJPannelGUI.ouvrirFichier();
    }//GEN-LAST:event_exitJMenuItemActionPerformed

    private void openFileJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileJMenuItemActionPerformed
		monClientJPannelGUI.arret();
		System.exit(0);
    }//GEN-LAST:event_openFileJMenuItemActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]){
		java.awt.EventQueue.invokeLater(new Runnable(){

			@Override
			public void run(){
				MainClient mainClient = new MainClient();
				try{
					UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
					SwingUtilities.updateComponentTreeUI(mainClient);
				} catch(ClassNotFoundException ex){
				} catch(InstantiationException ex){
				} catch(IllegalAccessException ex){
				} catch(UnsupportedLookAndFeelException ex){
				}
				mainClient.setVisible(true);
			}
		});
		/*
		JFrame monFrame = new JFrame("MonClient GUI");
		monFrame.setSize(800, 600);
		MonClientJPannelGUI mcGUI = new MonClientJPannelGUI();

		monFrame.add(mcGUI);
		monFrame.setVisible(true);
		 * */
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileJMenu;
    private javax.swing.JMenu editJMenu;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private fr.prunetwork.network.client.MonClientJPannelGUI monClientJPannelGUI;
    private javax.swing.JMenuItem openFileJMenuItem;
    // End of variables declaration//GEN-END:variables
}
