/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KanbanPlanning.java
 *
 * Created on 9 janv. 2011, 03:25:52
 */

package fr.prunetwork.atelierkanban.gui;

/**
 *
 * @author jpierre03
 */
public class KanbanPlanningPanel extends javax.swing.JPanel {

    /** Creates new form KanbanPlanning */
    public KanbanPlanningPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.CardLayout());

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setText("<table style=\"text-align: left; width: 174px; height: 144px;\" border=\"1\"\n       cellpadding=\"2\" cellspacing=\"2\">\n    <tbody>\n        <tr>\n            <td style=\"vertical-align: top; width: 16px;\"><br>\n            </td>\n            <td style=\"vertical-align: top; width: 985px;\"><br>\n            </td>\n        </tr>\n        <tr>\n            <td\n                style=\"vertical-align: top; width: 16px; background-color: red;\"><br>\n            </td>\n            <td style=\"vertical-align: top; width: 985px;\"><br>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"vertical-align: top; width: 16px;\"><br>\n            </td>\n            <td style=\"vertical-align: top; width: 985px;\"><br>\n            </td>\n        </tr>\n        <tr>\n            <td\n                style=\"vertical-align: top; width: 16px; background-color: rgb(51, 204, 0);\"><br>\n            </td>\n            <td\n                style=\"vertical-align: top; width: 985px; background-color: rgb(102, 102, 102);\"><br>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"vertical-align: top; width: 16px;\"><br>\n            </td>\n            <td\n                style=\"vertical-align: top; width: 985px; background-color: rgb(102, 102, 102);\"><br>\n            </td>\n        </tr>\n    </tbody>\n</table>");
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
